---
##############################################
##### Configuration for analysis scripts #####
##############################################

###
### Tools
###
condabase_script: /hidef/mambaforge/etc/profile.d/conda.sh
conda_pbbioconda_env: /hidef/bin/pbconda
wigToBigWig_bin: /hidef/bin/wigToBigWig
bcftools_bin: bcftools
samtools_bin: samtools
samtools_1.10_bin: /hidef/bin/samtools_1.10/samtools
seqkit_bin: /hidef/bin/seqkit
kmc_bindir: /hidef/bin/kmc/bin
gsutil_bin: [gsutil path]
HiDEFpipeline: /hidef/scripts
slurm_himemjob_options: --mem=320G
slurm_add_options:

###
#Genome reference information and files
###
genome: CHM13_v1
chrsizes: /hidef/references_CHM13v1/chrsizes.tsv
chrs_to_analyze: /hidef/references_CHM13v1/chrM.txt
Nrefbed: /hidef/references_CHM13v1/chm13.draft_v1.0.N.merged.bed
fastaref: [chm13.draft_v1.0.fasta]
genomemmiindex: [chm13.draft_v1.0.mmi]
BSgenomepackagename: BSgenome.Hsapiens.T2T.CHM13v1
gnomad_sensitivity_ref: /hidef/references_CHM13v1/af.only.0.001.gnomad.v3.1.2.CHM13_v1.bw

###
### Sample configuration
###
samplenames:
  - [sample name 1]
  - [sample name 2]

tissues:
  - [tissue 1]
  - [tissue 2]

barcodes:
  - bc####:XXXXXXXXXXXXXXXX
  - bc####:XXXXXXXXXXXXXXXX

###
### Configuration for process_subreads.sh
###
subreads_filename: [subreads.bam]
process_subreads_output_path: [processed reads output path]
ccs_BAM_prefix: [ccs_BAM_prefix]
ccschunks: 30
minccsrq: 0.99
minoverlap: 0.9
removetempdir: true

###
### Configuration for make_bamfilezmw_all.R
###

# Note: bamfilezmw_all_filename defines RDS output of make_bamfilezmw_all.R script and the input of downstream scripts
bamfilezmw_all_filename: [/fullpath/bamfilezmw_all.chrM.RDS]

# vcffile_filenames: VCF files for annotation of bamfilezmw_all in make_bamfilezmw_all.R script. Note these are usually the same as the VCFs in vcffilters.
make_bamfilezmw_all_config:
  [sample name 1]:
    vcffile_filenames:
      - [GATK.vcf.gz]
      - [deepvariant.vcf.gz]
  [sample name 2]:
    vcffile_filenames:
      - [GATK.vcf.gz]
      - [deepvariant.vcf.gz]

###
### Configuration for mutation filtering
###

#Bigwig cache directory (stores bigwig files that are used across analyses, to save time)
bigwig_cachedir: [bigwig_cachedir folder]

#Output basename and path
analysisoutput_basename: [analysisoutput_basename]
analysisoutput_path: [analysisoutput_path.chrM (make distinct from chr1-22X output path)]
gcloudoutput_path: [gcloud output path for final BAM files]

#Basic filters
# First sub-level is filter set index. List as many filter sets as desired, each under a consecutive integer index
thresholds:
  1:
    rqfwd: .99
    rqrev: .99
    rqavg: 0
    ecfwd: 5
    ecrev: 5
    ecavg: 0
    mapqfwd: 60
    mapqrev: 60
    mapqavg: 0
    numsnvsfwd: 999999
    numsnvsrev: 999999
    numsnvszmw: 999999
    numsnvsfwdrevdiff: 5
    numindelsfwd: 999999
    numindelsrev: 999999
    numindelszmw: 20
    numsnvsfwdpostVCF: 999999
    numsnvsrevpostVCF: 999999
    numsnvszmwpostVCF: 8
    numsoftclipfwd: 999999
    numsoftcliprev: 999999
    numsoftclipavg: 30
    minqq: 93
    bpends: 10
    ccsindelfilter: true
    ccsindelinspad: m2b15
    ccsindeldelpad: m2b15
    minsubreads_cvg_fraction: 0.5
    minZMWsubreadsVariantReads: 0
    minZMWsubreadsVAF: 0.5
    minssDNAsubreadsVariantReads: 0
    minssDNAsubreadsVAF: 0.5
  2:
    rqfwd: .999
    rqrev: .999
    rqavg: 0
    ecfwd: 20
    ecrev: 20
    ecavg: 0
    mapqfwd: 60
    mapqrev: 60
    mapqavg: 0
    numsnvsfwd: 999999
    numsnvsrev: 999999
    numsnvszmw: 999999
    numsnvsfwdrevdiff: 5
    numindelsfwd: 999999
    numindelsrev: 999999
    numindelszmw: 20
    numsnvsfwdpostVCF: 999999
    numsnvsrevpostVCF: 999999
    numsnvszmwpostVCF: 8
    numsoftclipfwd: 999999
    numsoftcliprev: 999999
    numsoftclipavg: 30
    minqq: 93
    bpends: 10
    ccsindelfilter: true
    ccsindelinspad: m2b15
    ccsindeldelpad: m2b15
    minsubreads_cvg_fraction: 0.5
    minZMWsubreadsVariantReads: 0
    minZMWsubreadsVAF: 0.6
    minssDNAsubreadsVariantReads: 0
    minssDNAsubreadsVAF: 0.6

#VCF filters
# First sub-level is filter set index (Index must match, and filters are used with, above filter set indexes)
#   However, if "..._sameforallbasicfiltersets" = true, then the below configuration for the first filter set will be used across all basic filter filter sets
# Second sub-level is samplenames.
# Third sub-level is vcffilter index (Can configure multiple vcf filters, with consecutive integer indexes.)
# Configure for each filter set and samplenames combination.
vcffilters_sameforallbasicfiltersets: true
vcffilters:
  1: 
    [sample name 1]:
      1:
        vcffilename: [GATK.vcf.gz]
        SNVFILTERS:
          - "."
        INDELFILTERS:
          - "."
        vcfSNVfilter: true
        vcfSNVDepth: 3
        vcfSNVGQ: 3
        vcfSNVVAF: 0.1
        vcfSNVQUAL: 3
        vcfINDELfilter: true
        vcfINDELDepth: 5
        vcfINDELGQ: 5
        vcfINDELVAF: 0.2
        vcfINDELQUAL: 10
        vcfINDELinspad: m2b15
        vcfINDELdelpad: m2b15
      2: 
        vcffilename: [Deepvariant.vcf.gz]
        SNVFILTERS:
          - "PASS"
        INDELFILTERS:
          - "PASS"
        vcfSNVfilter: true
        vcfSNVDepth: 3
        vcfSNVGQ: 3
        vcfSNVVAF: 0.1
        vcfSNVQUAL: 3
        vcfINDELfilter: true
        vcfINDELDepth: 3
        vcfINDELGQ: 3
        vcfINDELVAF: 0.1
        vcfINDELQUAL: 3
        vcfINDELinspad: m2b15
        vcfINDELdelpad: m2b15
    [sample name 2]:
      1:
        vcffilename: [GATK.vcf.gz]
        SNVFILTERS:
          - "."
        INDELFILTERS:
          - "."
        vcfSNVfilter: true
        vcfSNVDepth: 3
        vcfSNVGQ: 3
        vcfSNVVAF: 0.1
        vcfSNVQUAL: 3
        vcfINDELfilter: true
        vcfINDELDepth: 5
        vcfINDELGQ: 5
        vcfINDELVAF: 0.2
        vcfINDELQUAL: 10
        vcfINDELinspad: m2b15
        vcfINDELdelpad: m2b15
      2: 
        vcffilename: [Deepvariant.vcf.gz]
        SNVFILTERS:
          - "PASS"
        INDELFILTERS:
          - "PASS"
        vcfSNVfilter: true
        vcfSNVDepth: 3
        vcfSNVGQ: 3
        vcfSNVVAF: 0.1
        vcfSNVQUAL: 3
        vcfINDELfilter: true
        vcfINDELDepth: 3
        vcfINDELGQ: 3
        vcfINDELVAF: 0.1
        vcfINDELQUAL: 3
        vcfINDELinspad: m2b15
        vcfINDELdelpad: m2b15

#Bigwig filters
# First sub-level is filter set index (Index must match, and filters are used with, above filter set indexes)
#   However, if "..._sameforallbasicfiltersets" = true, then the below configuration for the first filter set will be used across all basic filter filter sets
# Second sub-level is bigwigfilter index (Can configure multiple bigwig filters, with consecutive integer indexes.)
# Configure for each filter set.
bigwigfilters_sameforallbasicfiltersets: true
bigwigfilters:
  1:
    1: 
      bigwigfiltertype: ZMW
      bigwigfile: /hidef/references_CHM13v1/k50.umap.sorted.bw
      binsize: 20
      threshold: lt0.4
      zmwthreshold: gte0.3
      padding: null
      applyto: null
    2: 
      bigwigfiltertype: ZMW
      bigwigfile: /hidef/references_CHM13v1/chm13.draft_v1.0.telomere.bw
      binsize: 1
      threshold: gte0.1
      zmwthreshold: gte0.00001
      padding: null
      applyto: null
    3: 
      bigwigfiltertype: ZMW
      bigwigfile: /hidef/references_CHM13v1/chm13.draft_v1.0.Satellite.merged.bw
      binsize: 1
      threshold: gte0.1
      zmwthreshold: gte0.2
      padding: null
      applyto: null
    4: 
      bigwigfiltertype: ZMW
      bigwigfile: [orphan_cov_all.CHM13_v1.bw]
      binsize: 20
      threshold: gte0.15
      zmwthreshold: gte0.2
      padding: null
      applyto: null
    5: 
      bigwigfiltertype: SNV
      bigwigfile: /hidef/references_CHM13v1/chm13.draft_v1.0.Satellite.merged.bw
      binsize: 1
      threshold: gte0.1
      zmwthreshold: null
      padding: 0
      applyto: both
    6: 
      bigwigfiltertype: SNV
      bigwigfile: /hidef/references_CHM13v1/k100.umap.sorted.bw
      binsize: 20
      threshold: lt0.95
      zmwthreshold: null
      padding: 0
      applyto: both
    7: 
      bigwigfiltertype: SNV
      bigwigfile: [prop_cov_all.CHM13_v1.bw]
      binsize: 20
      threshold: lt0.7
      zmwthreshold: null
      padding: 0
      applyto: both
    8: 
      bigwigfiltertype: SNV
      bigwigfile: [orphan_cov_all.CHM13_v1.bw]
      binsize: 20
      threshold: gte0.2
      zmwthreshold: null
      padding: 0
      applyto: both
    9: 
      bigwigfiltertype: SNV
      bigwigfile: [clip_all.CHM13_v1.bw]
      binsize: 200
      threshold: gte0.009
      zmwthreshold: null
      padding: 0
      applyto: both
    10: 
      bigwigfiltertype: SNV
      bigwigfile: /hidef/references_CHM13v1/1542.markdup.sorted.mapq0.bw
      binsize: 20
      threshold: gte0.1
      zmwthreshold: null
      padding: 0
      applyto: both
    11: 
      bigwigfiltertype: SNV
      bigwigfile: /hidef/references_CHM13v1/af.only.0.001.gnomad.v3.1.2.CHM13_v1.bw
      binsize: 1
      threshold: gte0.1
      zmwthreshold: null
      padding: 0
      applyto: both

#Germline BAM/CRAM filters
# First sub-level is filter set index (Index must match, and filters are used with, above filter set indexes)
#   However, if "..._sameforallbasicfiltersets" = true, then the below configuration for the first filter set will be used across all basic filter filter sets
# Second sub-level is samplesnames
# Configure for each filter set and samplenames combination.
bamfilters_sameforallbasicfiltersets: true
bamfilters:
  1:
    [Sample name 1]:
      bamfile: [Germline CRAM file]
      bamreftype: Illumina
      WGScoveragebigwig: [Germline coverage.bw file]
      minBAMTotalReads: 15
      maxBAMVariantReads: 3
      maxBAMVAF: 0.05
    [Sample name 2]:
      bamfile: [Germline CRAM file]
      bamreftype: Illumina
      WGScoveragebigwig: [Germline coverage.bw file]
      minBAMTotalReads: 15
      maxBAMVariantReads: 3
      maxBAMVAF: 0.05

#Mutation rate calculation filters
mutratefilters:
  maxmutationsperssdna: 1
  maxmutationsperzmw: 1
